/**
 * Settings navigation: every tab, section and searchable control the
 * Settings panel exposes. Tabs and sections are the single source of truth
 * in `@marinara-engine/shared` (`constants/settings-registry.ts`) so the
 * server can also point at a real setting label without a second list; this
 * file re-exports them and owns the client-only searchable-control catalog.
 *
 * Extracted from `components/panels/SettingsPanel.tsx` so surfaces that only
 * need to *point at* a setting — the omnibar, Professor Mari — can read it
 * without importing the 8500-line panel. Nothing here renders, imports an icon
 * or touches a store, so it stays cheap to depend on.
 *
 * Adding a setting: add it here and the omnibar finds it. There is no second
 * list to update. `omnibar-settings.test.ts` fails if a row ever points at an
 * id this file does not define.
 */
import {
  SETTINGS_SECTION_BY_ID,
  SETTINGS_SECTIONS,
  SETTINGS_TABS,
  type SettingsSectionId,
  type SettingsSectionMeta,
} from "@marinara-engine/shared";

export type { SettingsTabId, SettingsSectionId, SettingsSectionMeta } from "@marinara-engine/shared";
export { SETTINGS_TABS, SETTINGS_SECTIONS, SETTINGS_SECTION_BY_ID } from "@marinara-engine/shared";

/**
 * Owned here rather than in `ui.store` so this module stays free of store
 * imports. `ui.store` re-exports it for the callers that set it as a jump
 * target.
 */
export const QUICK_REPLIES_SETTINGS_CONTROL_ID = "quick-replies" as const;

/**
 * Q2: the settings that live in the omnibar's own view rather than in the Settings panel. A
 * jump to this section, or to one of its controls, opens that view instead of the panel.
 */
export const OMNIBAR_SETTINGS_SECTION_ID = "omnibar" satisfies SettingsSectionId;

export function isOmnibarSettingsTarget(target: { sectionId?: string | null; controlId?: string | null }): boolean {
  if (target.sectionId === OMNIBAR_SETTINGS_SECTION_ID) return true;
  if (!target.controlId) return false;
  return SETTINGS_SEARCHABLE_CONTROLS.some(
    (control) => control.id === target.controlId && control.sectionId === OMNIBAR_SETTINGS_SECTION_ID,
  );
}

/**
 * "Tab › Section" for a section, so a row away from the Settings panel (the
 * omnibar) can still say where a setting lives. Both pieces are the registry's
 * English; the caller localizes the same way the rest of this module does.
 */
export function settingsLocationPath(
  sectionId: SettingsSectionId,
  localize: (englishText: string) => string,
): string | null {
  const section = SETTINGS_SECTION_BY_ID.get(sectionId);
  if (!section) return null;
  const tab = SETTINGS_TABS.find((entry) => entry.id === section.tab);
  const sectionLabel = localize(section.label);
  return tab ? `${localize(tab.label)} › ${sectionLabel}` : sectionLabel;
}

export type SettingsControlKind = "Toggle" | "Slider" | "Select" | "Input" | "Picker" | "Button group";

export type SettingsSearchableControlMeta = {
  id: string;
  sectionId: SettingsSectionId;
  label: string;
  description: string;
  aliases: string[];
  /**
   * Looser synonyms a user might type instead of the label ("bigger text" for
   * Chat Font Size). Scored below a label/alias match in the omnibar
   * (`omnibar-search.ts`) so the setting's own name still wins cleanly.
   */
  keywords?: string[];
  kind: SettingsControlKind;
};

export type SettingsSearchResult =
  | { type: "section"; section: SettingsSectionMeta }
  | { type: "control"; control: SettingsSearchableControlMeta; section: SettingsSectionMeta };

export const SETTINGS_SEARCHABLE_CONTROLS: readonly SettingsSearchableControlMeta[] = [
  {
    id: "hide-chat-help-button",
    sectionId: "application",
    label: "Hide chat Help button",
    description: "Remove the Help button from Conversation, Roleplay, and Game chats.",
    aliases: ["help", "guide", "tutorial", "overlay", "question mark"],
    keywords: ["remove help", "hide tutorial"],
    kind: "Toggle",
  },
  {
    id: "language",
    sectionId: "application",
    label: "Language",
    description: "Choose the app language.",
    aliases: ["locale", "translation"],
    kind: "Select",
  },
  {
    id: "docs-language",
    sectionId: "application",
    label: "Documentation Language",
    description: "Choose the language for Marinara's built-in guides.",
    aliases: [
      "documentation",
      "guides",
      "docs",
      "manual",
      "spanish",
      "español",
      "german",
      "deutsch",
      "french",
      "français",
      "portuguese",
      "português",
      "brazilian",
      "polish",
      "polski",
      "russian",
      "русский",
      "japanese",
      "日本語",
      "korean",
      "한국어",
      "chinese",
      "simplified",
      "简体中文",
      "中文",
      "hindi",
      "हिन्दी",
    ],
    kind: "Select",
  },
  {
    id: "confirm-before-delete",
    sectionId: "application",
    label: "Confirm before deleting",
    description: "Ask before permanently deleting chats, characters, or other items.",
    aliases: ["delete", "confirmation", "safety"],
    keywords: ["are you sure", "delete warning"],
    kind: "Toggle",
  },
  {
    id: "android-status-bar",
    sectionId: "application",
    label: "Android status bar",
    description: "Show the time, battery level, and notification icons in the Android app.",
    aliases: ["android", "battery", "clock", "time", "notifications", "fullscreen"],
    kind: "Toggle",
  },
  {
    id: "achievements",
    sectionId: "application",
    label: "Achievements",
    description: "Show the Home achievements button and unlock notifications.",
    aliases: ["home", "badges", "unlock"],
    kind: "Toggle",
  },
  {
    id: "music-player",
    sectionId: "application",
    label: "Music Player",
    description: "Show the compact Music Player.",
    aliases: ["spotify", "youtube", "music dj"],
    kind: "Toggle",
  },
  // Q2: everything below up to "notification-position" lives in the omnibar's settings view
  // (`OmnibarSettingsMenu.tsx`), in its order: Search, Quick answers, Professor Mari, Around the app, Appearance.
  {
    id: "omnibar-suggestions",
    sectionId: "omnibar",
    label: "Offer to improve a field",
    description: "While you edit a field, Search offers to have Professor Mari improve it.",
    aliases: ["context suggestions", "omnibar suggestions", "proactive suggestions", "search"],
    kind: "Toggle",
  },
  {
    id: "omnibar-search-history",
    sectionId: "omnibar",
    label: "Search history",
    description: "Search lists the results you pick most first. Kept on this device only.",
    aliases: ["clear search history", "recent", "forget", "frecency"],
    kind: "Button group",
  },
  {
    id: "quick-answers",
    sectionId: "omnibar",
    label: "Quick answers in Search",
    description:
      "When you type a question, Professor Mari answers in up to three sentences from the docs. She sees only what you typed and changes nothing.",
    aliases: ["quick answers", "aside", "dead end", "ask mari", "answer when search finds nothing"],
    kind: "Toggle",
  },
  {
    id: "quick-answer-model",
    sectionId: "omnibar",
    label: "Answer with",
    description: "Gets only your search text, never your chats, memories or the field you edit.",
    aliases: ["quick answer model", "quick answer connection", "local model"],
    kind: "Select",
  },
  {
    id: "quick-answer-delay",
    sectionId: "omnibar",
    label: "Wait after typing",
    description: "How long Search waits before Professor Mari writes a quick answer.",
    aliases: ["quick answer delay", "delay", "seconds"],
    kind: "Button group",
  },
  {
    id: "ask-mari",
    sectionId: "omnibar",
    label: "Ask Professor Mari from Search",
    description: "Open her from the Search field, the pull-down or Ctrl/Command+J.",
    aliases: ["professor mari", "mari assistance", "assistant", "ctrl j"],
    kind: "Toggle",
  },
  {
    id: "professor-mari-suggestions",
    sectionId: "omnibar",
    label: "Reply chips",
    description: "Show quick replies under her answers.",
    aliases: ["professor mari suggestions", "mari", "chips", "next steps"],
    kind: "Toggle",
  },
  {
    id: "mari-permissions-mode",
    sectionId: "omnibar",
    label: "Professor Mari permissions mode",
    description:
      "When Professor Mari may stage or apply workspace changes: Auto, Manual, Accept edits, Plan, or Bypass.",
    aliases: ["mari", "permissions", "mode", "plan", "bypass", "accept", "manual", "approve"],
    kind: "Select",
  },
  {
    id: "mari-edit-view",
    sectionId: "omnibar",
    label: "Change cards open in",
    description: "Easy shows a summary. Raw shows every field.",
    aliases: ["mari", "easy", "raw", "review", "diff"],
    kind: "Button group",
  },
  {
    id: "mari-send-on-enter",
    sectionId: "omnibar",
    label: "Enter sends to Professor Mari",
    description: "When off, Enter adds a new line and Ctrl/Command+Enter sends.",
    aliases: ["mari", "send on enter", "enter to send", "enter key"],
    kind: "Toggle",
  },
  {
    id: "mini-mari",
    sectionId: "omnibar",
    label: "Mini Professor Mari visits",
    description: "A small Professor Mari sometimes drops in with a message while you scroll.",
    aliases: ["mini mari surprise visits", "chibi", "professor", "surprise"],
    kind: "Toggle",
  },
  {
    id: "mari-appearance-pack",
    sectionId: "omnibar",
    label: "Professor Mari appearance",
    description: "How Professor Mari looks in her chat, Search, Home and the top bar.",
    aliases: ["appearance pack", "mari look", "pack", "basic", "dottore", "golden", "safari"],
    kind: "Picker",
  },
  {
    id: "notification-position",
    sectionId: "notifications",
    label: "Notification position",
    description: "Choose where error messages and other notifications appear.",
    aliases: ["error", "toast", "top", "bottom", "position"],
    keywords: ["toast position", "alert location"],
    kind: "Select",
  },
  {
    id: "notification-conversation-sound",
    sectionId: "notifications",
    label: "Conversation mode notification sound",
    description: "Play a ping for Conversation replies.",
    aliases: ["sound", "ping", "convo"],
    keywords: ["message sound", "chat ping"],
    kind: "Toggle",
  },
  {
    id: "notification-roleplay-sound",
    sectionId: "notifications",
    label: "Roleplay mode notification sound",
    description: "Play a ping for Roleplay replies.",
    aliases: ["sound", "ping", "rp"],
    kind: "Toggle",
  },
  {
    id: "notification-game-sound",
    sectionId: "notifications",
    label: "Game mode notification sound",
    description: "Play a ping for Game replies.",
    aliases: ["sound", "ping"],
    kind: "Toggle",
  },
  {
    id: "notification-unfocused-only",
    sectionId: "notifications",
    label: "Only when Marinara is unfocused",
    description: "Play notification sounds only while Marinara is not focused.",
    aliases: ["sound", "background", "unfocused"],
    kind: "Toggle",
  },
  {
    id: "browser-background-notifications",
    sectionId: "notifications",
    label: "Background replies browser notifications",
    description: "Show browser notifications for background Conversation replies.",
    aliases: ["browser", "notifications", "conversation"],
    keywords: ["desktop notification", "push notification"],
    kind: "Toggle",
  },
  {
    id: "mobile-background-notifications",
    sectionId: "notifications",
    label: "Background replies mobile notifications",
    description: "Show native Android notifications for background Conversation replies.",
    aliases: ["mobile", "android", "notifications", "conversation"],
    keywords: ["push notification", "phone alert"],
    kind: "Toggle",
  },
  {
    id: "enable-streaming",
    sectionId: "responses",
    label: "Enable streaming",
    description: "Show AI responses as they generate.",
    aliases: ["stream", "typewriter", "response"],
    keywords: ["streaming", "typing effect"],
    kind: "Toggle",
  },
  {
    id: "streaming-speed",
    sectionId: "responses",
    label: "Streaming speed",
    description: "Tune how fast streamed tokens appear.",
    aliases: ["speed", "typewriter", "tokens"],
    keywords: ["typing speed", "typewriter speed"],
    kind: "Slider",
  },
  {
    id: "trim-incomplete-output",
    sectionId: "responses",
    label: "Trim incomplete sentences from the response",
    description: "Trim trailing unfinished sentences from AI responses.",
    aliases: ["trim", "unfinished", "sentence"],
    kind: "Toggle",
  },
  {
    id: "continue-adds-newline",
    sectionId: "responses",
    label: "Add a new line before /continue text",
    description: "Start /continue text after a blank line.",
    aliases: ["continue", "newline", "blank line"],
    kind: "Toggle",
  },
  {
    id: "messages-per-page",
    sectionId: "responses",
    label: "Messages per page",
    description: "Control how many messages load at once.",
    aliases: ["pagination", "load more", "history"],
    // F6 (O5): "context"/"history length" sent a user trying to raise the model's
    // context size here instead - there is no context-SIZE control in this
    // registry (that lives in connection/preset parameters), so those two keywords
    // only misdirected the search.
    keywords: ["load history"],
    kind: "Input",
  },
  {
    id: "send-on-enter",
    sectionId: "input-editing",
    label: "Send on Enter",
    description: "Choose where Enter sends your message instead of adding a new line.",
    aliases: ["enter to send", "enter key", "new line", "ctrl enter"],
    keywords: ["shift enter sends", "enter sends message"],
    kind: "Button group",
  },
  {
    id: "keep-guidance-after-regenerating",
    sectionId: "input-editing",
    label: "Keep guidance after regenerating",
    description: "Leave your direction in the chat box after a guided regenerate, so you can adjust it and try again.",
    aliases: ["guided", "regenerate", "draft", "clear"],
    kind: "Toggle",
  },
  {
    id: "add-cyoa-choices-to-message",
    sectionId: "input-editing",
    label: "Add CYOA choices to the message box",
    description: "Clicking a CYOA choice adds it to the message box instead of sending it.",
    aliases: ["cyoa", "choices", "draft", "combine"],
    kind: "Toggle",
  },
  {
    id: "speech-to-text",
    sectionId: "input-editing",
    label: "Speech-to-text microphone",
    description: "Show a microphone button in chat inputs.",
    aliases: ["microphone", "dictation", "speech"],
    keywords: ["voice typing", "talk to text"],
    kind: "Toggle",
  },
  {
    id: "intuitive-swipe-navigation",
    sectionId: "input-editing",
    label: "Intuitive swipe navigation",
    description: "Use keyboard arrows or touch swipes to move between generations.",
    aliases: ["swipes", "arrows", "alternate generations"],
    keywords: ["alt generations", "regenerate navigation"],
    kind: "Toggle",
  },
  {
    id: "reroll-past-newest-swipe",
    sectionId: "input-editing",
    label: "Reroll past the newest swipe",
    description: "Create a reroll when swiping past the newest assistant message.",
    aliases: ["swipe", "reroll", "regenerate"],
    kind: "Toggle",
  },
  {
    id: "up-arrow-edits-last-message",
    sectionId: "input-editing",
    label: "Up Arrow edits last message",
    description: "Open the most recent message for editing with Up Arrow.",
    aliases: ["keyboard", "edit", "shortcut"],
    kind: "Toggle",
  },
  {
    id: "double-click-edits-messages",
    sectionId: "input-editing",
    label: "Double-click edits messages",
    description: "Edit Roleplay messages with double-click or double-tap.",
    aliases: ["double tap", "edit", "roleplay"],
    kind: "Toggle",
  },
  {
    id: "bold-dialogue",
    sectionId: "text-rules",
    label: "Bold dialogue in quotes",
    description: "Bold quoted dialogue text in chat display.",
    aliases: ["quotes", "dialogue", "formatting"],
    kind: "Toggle",
  },
  {
    id: "convert-latex-symbols",
    sectionId: "text-rules",
    label: "Convert LaTeX symbols",
    description: "Display common LaTeX commands as regular symbols.",
    aliases: ["math", "symbols", "formatting"],
    kind: "Toggle",
  },
  {
    id: "quote-style",
    sectionId: "text-rules",
    label: "Quote style",
    description: "Choose how quotation marks are unified.",
    aliases: ["quotes", "dialogue", "punctuation"],
    kind: "Button group",
  },
  {
    id: "color-inline-names",
    sectionId: "text-rules",
    label: "Color Character Names in Text",
    description: "Color character names and aliases inline in message text.",
    aliases: ["names", "aliases", "color", "gradient", "characters"],
    kind: "Toggle",
  },
  {
    id: "disable-inline-name-gradients",
    sectionId: "text-rules",
    label: "Force Solid Colors for Inline Names",
    description: "Replace gradient name colors with the brightest solid color inline.",
    aliases: ["gradient", "solid", "names", "readability"],
    kind: "Toggle",
  },
  {
    id: "game-instant-text-reveal",
    sectionId: "game-playback",
    label: "Instantly reveal game text",
    description: "Skip the Game mode narration typewriter effect.",
    aliases: ["game", "typewriter", "instant"],
    keywords: ["skip typewriter", "instant text"],
    kind: "Toggle",
  },
  {
    id: "game-middle-mouse-navigation",
    sectionId: "game-playback",
    label: "Mouse-wheel + click navigation",
    description: "Navigate Game mode with mouse wheel and background clicks.",
    aliases: ["middle mouse", "scroll", "game navigation"],
    kind: "Toggle",
  },
  {
    id: "game-narration-speed",
    sectionId: "game-playback",
    label: "Game narration speed",
    description: "Tune the Game mode narration typewriter speed.",
    aliases: ["game", "typewriter", "speed"],
    keywords: ["narration speed", "text speed"],
    kind: "Slider",
  },
  {
    id: "game-auto-play-delay",
    sectionId: "game-playback",
    label: "Game auto-play segment delay",
    description: "Pause between Game mode auto-play narration segments.",
    aliases: ["autoplay", "game", "delay"],
    kind: "Slider",
  },
  {
    id: "queue-media-generation",
    sectionId: "overall-generations",
    label: "Queue media generation requests",
    description: "Send image and video generation jobs one at a time per connection.",
    aliases: ["media", "image", "video", "queue", "generation"],
    kind: "Toggle",
  },
  {
    id: "image-prompt-review",
    sectionId: "overall-generations",
    label: "Expose media prompts before sending",
    description: "Review generated image and Gallery video prompts before sending.",
    aliases: [
      "image",
      "video",
      "media",
      "prompt",
      "review",
      "selfie",
      "noodle",
      "avatar",
      "portrait",
      "sprite",
      "animated expression",
    ],
    keywords: ["review image prompt", "approve image"],
    kind: "Toggle",
  },
  {
    id: "image-background-size",
    sectionId: "image-generation",
    label: "Background image size",
    description: "Set default generated background dimensions.",
    aliases: ["image", "resolution", "canvas"],
    kind: "Input",
  },
  {
    id: "image-illustration-size",
    sectionId: "image-generation",
    label: "Illustration image size",
    description: "Set default generated illustration dimensions.",
    aliases: ["image", "resolution", "canvas", "illustrator"],
    kind: "Input",
  },
  {
    id: "image-game-size",
    sectionId: "image-generation",
    label: "Game scene image size",
    description: "Set the default dimensions for generated Game scene illustrations.",
    aliases: ["image", "resolution", "canvas", "game", "illustrator"],
    kind: "Input",
  },
  {
    id: "image-portrait-size",
    sectionId: "image-generation",
    label: "Portrait image size",
    description: "Set default generated portrait dimensions.",
    aliases: ["image", "resolution", "canvas", "character"],
    kind: "Input",
  },
  {
    id: "image-character-sheet-size",
    sectionId: "image-generation",
    label: "Character sheets",
    description: "Set character reference sheet dimensions independently of backgrounds.",
    aliases: ["image", "resolution", "canvas", "character", "reference", "sheet"],
    kind: "Input",
  },
  {
    id: "image-selfie-size",
    sectionId: "image-generation",
    label: "Selfie image size",
    description: "Set default generated selfie dimensions.",
    aliases: ["image", "resolution", "canvas", "conversation"],
    kind: "Input",
  },
  {
    id: "image-style-profiles",
    sectionId: "image-generation",
    label: "Style Profiles",
    description: "Tune reusable image prompt style profiles.",
    aliases: ["image", "style", "danbooru", "anime", "realistic"],
    keywords: ["art style", "image style"],
    kind: "Select",
  },
  {
    id: "video-scene-duration",
    sectionId: "video-generation",
    label: "Scene video fallback length",
    description: "Set fallback duration for generated scene videos.",
    aliases: ["video", "duration", "length"],
    kind: "Input",
  },
  {
    id: "video-animated-expression-duration",
    sectionId: "video-generation",
    label: "Animated expression length",
    description: "Set animated expression clip duration.",
    aliases: ["video", "expression", "sprite", "duration"],
    kind: "Input",
  },
  {
    id: "visual-theme",
    sectionId: "app-style",
    label: "Visual Style",
    description: "Switch between Marinara and SillyTavern visual themes.",
    aliases: ["theme", "style", "sillytavern", "marinara"],
    keywords: ["skin", "look and feel"],
    kind: "Button group",
  },
  {
    id: "theme-mode",
    sectionId: "app-style",
    label: "Color Scheme",
    description: "Switch between dark and light mode.",
    aliases: ["theme", "dark", "light", "mode"],
    keywords: ["dark", "night", "light", "day"],
    kind: "Select",
  },
  {
    id: "desktop-sidebar-width",
    sectionId: "app-style",
    label: "Desktop sidebar width",
    description:
      "Adjust both desktop sidebars. Their contents adapt to the available space; mobile panels keep their existing layout.",
    aliases: ["sidebar", "width", "resize", "left panel", "right panel"],
    kind: "Slider",
  },
  {
    id: "custom-cursor",
    sectionId: "app-style",
    label: "Custom Mouse Pointer",
    description: "Use Marinara's accent-colored cursor.",
    aliases: ["cursor", "mouse", "pointer"],
    keywords: ["custom pointer"],
    kind: "Toggle",
  },
  {
    id: "reduce-ambient-effects",
    sectionId: "app-style",
    label: "Reduce Ambient Animations & Effects",
    description: "Stop decorative animation, particles, and text reveal.",
    aliases: ["reduced motion", "animation", "particles", "effects"],
    keywords: ["reduced ambient effects", "less motion"],
    kind: "Toggle",
  },
  {
    id: "app-background-color",
    sectionId: "app-style",
    label: "Background Color",
    description: "Set the main app shell background color.",
    aliases: ["background", "theme", "gradient"],
    keywords: ["wallpaper", "app color"],
    kind: "Picker",
  },
  {
    id: "app-accent-color",
    sectionId: "app-style",
    label: "Accent Color",
    description: "Set the shared app accent color.",
    aliases: ["primary", "theme", "highlight"],
    keywords: ["brand color", "ui color"],
    kind: "Picker",
  },
  {
    id: "accent-pulse",
    sectionId: "app-style",
    label: "Accent Pulse",
    description: "Animate the selected accent color.",
    aliases: ["accent", "animation", "motion"],
    keywords: ["pulsing color", "breathing glow"],
    kind: "Toggle",
  },
  {
    id: "rgb-mode",
    sectionId: "app-style",
    label: "RGB Mode",
    description: "Cycle the app accent through Marinara's rainbow palette.",
    aliases: ["rainbow", "accent", "color"],
    keywords: ["rainbow mode", "color cycle"],
    kind: "Toggle",
  },
  {
    id: "chat-widget-style",
    sectionId: "app-style",
    label: "Chat widget style",
    description:
      "Choose a look for movable chat buttons, windows and sections. Picking a preset resets Font, Shape and Colors. Professor Mari can create custom themes for you.",
    aliases: ["dottore", "mari", "preset", "window", "drawer", "button", "sci-fi", "fantasy"],
    kind: "Button group",
  },
  {
    id: "chat-widget-border-color",
    sectionId: "app-style",
    label: "Border & Buttons Color",
    description: "Set chat widget outlines and button icon colors.",
    aliases: ["widget", "window", "drawer", "color", "gradient"],
    kind: "Picker",
  },
  {
    id: "chat-widget-background-color",
    sectionId: "app-style",
    label: "Widget Background Color",
    description: "Set backgrounds for chat windows, sections and buttons.",
    aliases: ["widget", "window", "drawer", "color", "gradient"],
    kind: "Picker",
  },
  {
    id: "chat-widget-text-color",
    sectionId: "app-style",
    label: "Widget Text Color",
    description: "Set chat widget text colors and gradients.",
    aliases: ["widget", "window", "drawer", "color", "gradient"],
    kind: "Picker",
  },
  {
    id: "chat-widget-button-size",
    sectionId: "app-style",
    label: "Button size (px)",
    description:
      "Resize movable chat buttons and their icons independently of Display Size. Reset to keep the current default.",
    aliases: ["widget", "icon", "scale", "pixels", "size", "movable", "tracker", "map"],
    kind: "Input",
  },
  {
    id: "chat-widget-font",
    sectionId: "app-style",
    label: "Chat widget font",
    description: "Choose lettering for chat windows and sections.",
    aliases: ["typography", "typeface", "serif", "monospace", "window", "drawer"],
    kind: "Select",
  },
  {
    id: "chat-widget-shape",
    sectionId: "app-style",
    label: "Chat widget shape",
    description: "Change the frame shape without changing the colors.",
    aliases: ["rounded", "square", "cut corner", "arched", "window", "drawer", "button"],
    kind: "Select",
  },
  {
    id: "font-family",
    sectionId: "text-scale",
    label: "Font",
    description: "Choose the font used across the app.",
    aliases: ["typography", "typeface"],
    keywords: ["typeface", "font style"],
    kind: "Select",
  },
  {
    id: "chat-widget-apply-font",
    sectionId: "app-style",
    label: "Apply preset font",
    description: "Use the selected widget font for chat messages, input boxes and controls.",
    aliases: ["widget", "message", "composer", "typography", "dottore", "mari"],
    kind: "Toggle",
  },
  {
    id: "chat-widget-apply-shape",
    sectionId: "app-style",
    label: "Apply preset shape",
    description: "Use widget shapes for chat boxes and controls. Conversation messages keep their own shape.",
    aliases: ["widget", "message", "composer", "rounded", "cut corner", "arched"],
    kind: "Toggle",
  },
  {
    id: "chat-widget-apply-colors",
    sectionId: "app-style",
    label: "Apply preset colors",
    description: "Use widget colors and custom gradients for chat messages, input boxes and controls.",
    aliases: ["widget", "message", "composer", "gradient", "dottore", "mari"],
    kind: "Toggle",
  },
  {
    id: "display-size",
    sectionId: "text-scale",
    label: "Display Size",
    description: "Adjust the base font size across the app.",
    aliases: ["font size", "scale", "readability"],
    keywords: ["zoom", "scale ui"],
    kind: "Select",
  },
  {
    id: "chat-font-size",
    sectionId: "text-scale",
    label: "Chat Font Size",
    description: "Adjust the font size of chat messages.",
    aliases: ["text size", "message size", "readability"],
    keywords: ["bigger text", "smaller text", "font size"],
    kind: "Slider",
  },
  {
    id: "chat-text-color",
    sectionId: "text-scale",
    label: "Chat Text Color",
    description: "Control the main chat message text color.",
    aliases: ["font color", "message color"],
    keywords: ["message text color"],
    kind: "Picker",
  },
  {
    id: "default-dialogue-color",
    sectionId: "text-scale",
    label: "Default Dialogue Color",
    description: "Choose the dialogue highlight used by cards without their own dialogue color.",
    aliases: ["quote color", "character dialogue", "persona dialogue"],
    kind: "Toggle",
  },
  {
    id: "chat-chrome-text-color",
    sectionId: "text-scale",
    label: "Chat Chrome Text Color",
    description: "Control ordinary chrome copy color in chat-adjacent UI.",
    aliases: ["chrome", "text color", "tracker"],
    kind: "Picker",
  },
  {
    id: "text-outline-width",
    sectionId: "text-scale",
    label: "Text Outline / Stroke",
    description: "Tune chat text outline width and color.",
    aliases: ["stroke", "outline", "readability"],
    keywords: ["text stroke", "text border"],
    kind: "Slider",
  },
  {
    id: "conversation-layout",
    sectionId: "chat-display",
    label: "Chat Layout",
    description: "Switch Conversation messages between linear rows and bubbles.",
    aliases: ["conversation", "bubbles", "linear"],
    keywords: ["chat bubbles", "message layout"],
    kind: "Button group",
  },
  {
    id: "conversation-always-display-swipe-menu",
    sectionId: "chat-display",
    label: "Always display swipe menu",
    description:
      "Show swipe arrows and the counter from the first response. Turn off to show them only after regeneration.",
    aliases: ["conversation", "swipe", "regenerate", "arrows"],
    kind: "Toggle",
  },
  {
    id: "roleplay-always-display-swipe-menu",
    sectionId: "roleplay-messages",
    label: "Always display swipe menu",
    description:
      "Show swipe arrows and the counter from the first response. Turn off to show them only after regeneration.",
    aliases: ["roleplay", "swipe", "regenerate", "arrows"],
    kind: "Toggle",
  },
  {
    id: "conversation-avatar-shape",
    sectionId: "chat-display",
    label: "Avatar Shape",
    description: "Choose circular or square avatars in Conversation mode.",
    aliases: ["conversation", "avatar", "circle", "square"],
    kind: "Button group",
  },
  {
    id: "show-characters-in-persona-pickers",
    sectionId: "message-tools",
    label: "Show Characters in Persona Pickers",
    description: "Allow character cards to appear as user identities in chat.",
    aliases: ["persona", "character", "play as", "identity"],
    kind: "Toggle",
  },
  {
    id: "tracker-panel",
    sectionId: "roleplay-tracker",
    label: "Tracker Panel",
    description: "Show or hide the Roleplay HUD tracker panel.",
    aliases: ["tracker", "hud", "roleplay"],
    keywords: ["hud", "stat panel"],
    kind: "Toggle",
  },
  {
    id: "tracker-replace-hud-icons",
    sectionId: "roleplay-tracker",
    label: "Replace tracker HUD icons",
    description: "Hide the old world/player tracker icon strip.",
    aliases: ["tracker", "hud", "icons"],
    kind: "Toggle",
  },
  {
    id: "tracker-expression-sprites",
    sectionId: "roleplay-tracker",
    label: "Use expression sprites for tracker portraits",
    description: "Allow tracker portraits to use Expression Engine sprites.",
    aliases: ["tracker", "sprites", "portraits"],
    kind: "Toggle",
  },
  {
    id: "tracker-panel-background",
    sectionId: "roleplay-tracker",
    label: "Panel background",
    description: "Pick the Tracker panel background.",
    aliases: ["tracker", "background", "color"],
    kind: "Picker",
  },
  {
    id: "tracker-desktop-size",
    sectionId: "roleplay-tracker",
    label: "Desktop size",
    description: "Choose the Tracker panel desktop width.",
    aliases: ["tracker", "width", "compact", "expanded"],
    kind: "Button group",
  },
  {
    id: "tracker-thought-display-mode",
    sectionId: "roleplay-tracker",
    label: "Thought display mode",
    description: "Choose how featured character thoughts open.",
    aliases: ["tracker", "thoughts", "dock", "floating"],
    kind: "Button group",
  },
  {
    id: "tracker-stat-display-mode",
    sectionId: "roleplay-tracker",
    label: "Stat display mode",
    description: "Choose whether persona and character stats use compact bars or circular gauges.",
    aliases: ["tracker", "stats", "bars", "gauges", "circular"],
    kind: "Button group",
  },
  {
    id: "tracker-docked-thoughts",
    sectionId: "roleplay-tracker",
    label: "Always show Docked thoughts",
    description: "Keep docked tracker thoughts visible inside character cards.",
    aliases: ["tracker", "thoughts", "dock"],
    kind: "Toggle",
  },
  {
    id: "tracker-temperature-unit",
    sectionId: "roleplay-tracker",
    label: "Temperature unit",
    description: "Switch tracker temperature displays between Celsius and Fahrenheit.",
    aliases: ["tracker", "weather", "celsius", "fahrenheit"],
    kind: "Toggle",
  },
  {
    id: "roleplay-vn-display",
    sectionId: "roleplay-messages",
    label: "Visual Novel display",
    description: "Show one completed paragraph at a time above the composer.",
    aliases: ["roleplay", "vn", "visual novel", "classic", "presentation", "history"],
    kind: "Toggle",
  },
  {
    id: "roleplay-vn-autoplay",
    sectionId: "roleplay-messages",
    label: "Auto-play VN paragraphs",
    description: "Advance Roleplay Visual Novel paragraphs automatically, waiting for speech when it is playing.",
    aliases: ["roleplay", "vn", "autoplay", "tts", "speech", "reading"],
    kind: "Toggle",
  },
  {
    id: "roleplay-vn-autoplay-delay",
    sectionId: "roleplay-messages",
    label: "Paragraph delay",
    description: "Set the time between Roleplay Visual Novel paragraphs when auto-play is enabled.",
    aliases: ["roleplay", "vn", "autoplay", "delay", "reading"],
    kind: "Slider",
  },
  {
    id: "roleplay-vn-portrait-scale",
    sectionId: "roleplay-messages",
    label: "Dialogue portrait scale",
    description: "Adjust Roleplay Visual Novel portraits.",
    aliases: ["roleplay", "vn", "portrait", "scale"],
    kind: "Slider",
  },
  {
    id: "roleplay-vn-sprite-scale",
    sectionId: "roleplay-messages",
    label: "Full-body sprite scale",
    description: "Adjust Roleplay Visual Novel full-body sprites.",
    aliases: ["roleplay", "vn", "sprite", "scale"],
    kind: "Slider",
  },
  {
    id: "roleplay-chat-position",
    sectionId: "roleplay-messages",
    label: "Chat position",
    description: "Where the chat sits on wide screens. Has no effect on phones.",
    aliases: ["roleplay", "layout", "left", "right", "center", "centre", "align", "side", "column", "desktop"],
    kind: "Button group",
  },
  {
    id: "roleplay-message-opacity",
    sectionId: "roleplay-messages",
    label: "Roleplay Messages Background Opacity",
    description: "Adjust roleplay bubble background opacity.",
    aliases: ["roleplay", "opacity", "messages"],
    keywords: ["transparency", "message background"],
    kind: "Slider",
  },
  {
    id: "roleplay-reduced-paint-effects",
    sectionId: "roleplay-messages",
    label: "Reduced paint effects",
    description: "Flatten costly Roleplay transparency, shadows, and scene overlays.",
    aliases: ["roleplay", "performance", "firefox", "slow", "paint", "effects"],
    keywords: ["performance mode", "low end gpu"],
    kind: "Toggle",
  },
  {
    id: "show-roleplay-thinking-in-messages",
    sectionId: "roleplay-messages",
    label: "Show Thinking In Messages",
    description: "Show model reasoning above the response inside Roleplay message bubbles.",
    aliases: ["roleplay", "reasoning", "thinking", "thoughts", "messages"],
    keywords: ["reasoning visible", "chain of thought"],
    kind: "Toggle",
  },
  {
    id: "keep-roleplay-thinking-expanded",
    sectionId: "roleplay-messages",
    label: "Don't Collapse Thinking",
    description: "Keep inline model reasoning expanded when the response starts.",
    aliases: ["roleplay", "reasoning", "thinking", "collapse", "expanded"],
    kind: "Toggle",
  },
  {
    id: "scrollable-avatars",
    sectionId: "roleplay-messages",
    label: "Scrollable Avatars",
    description: "Keep roleplay avatars visible while scrolling long messages.",
    aliases: ["roleplay", "avatars", "sticky"],
    kind: "Toggle",
  },
  {
    id: "narrator-cycling-avatars",
    sectionId: "roleplay-messages",
    label: "Narrator's Cycling Avatars",
    description: "Cycle Narrator avatars or show active characters together.",
    aliases: ["roleplay", "narrator", "avatars", "cycle", "group"],
    kind: "Toggle",
  },
  {
    id: "roleplay-avatar-style",
    sectionId: "roleplay-messages",
    label: "Roleplay Avatars",
    description: "Choose how avatars sit next to roleplay messages.",
    aliases: ["avatar", "portrait", "circles", "rectangles"],
    kind: "Button group",
  },
  {
    id: "roleplay-avatar-scale",
    sectionId: "roleplay-messages",
    label: "Message avatar scale",
    description: "Adjust the default roleplay message avatar scale.",
    aliases: ["avatar", "portrait", "scale"],
    kind: "Slider",
  },
  {
    id: "roleplay-sprite-scale",
    sectionId: "roleplay-messages",
    label: "Default sprite scale",
    description: "Adjust the default roleplay sprite scale.",
    aliases: ["sprite", "scale", "roleplay"],
    kind: "Slider",
  },
  {
    id: "game-dialogue-portrait-scale",
    sectionId: "game-presentation",
    label: "Dialogue portrait scale",
    description: "Adjust Game mode dialogue portrait scale.",
    aliases: ["game", "avatar", "portrait", "scale"],
    kind: "Slider",
  },
  {
    id: "game-full-body-sprite-scale",
    sectionId: "game-presentation",
    label: "Full-body sprite scale",
    description: "Adjust Game mode full-body sprite scale.",
    aliases: ["game", "sprite", "scale"],
    kind: "Slider",
  },
  {
    id: "chat-list-backgrounds",
    sectionId: "chat-backgrounds",
    label: "Chat list backgrounds",
    description: "Show each chat's background as a banner behind its row in the chat list.",
    aliases: ["sidebar", "chat list", "banner", "background", "row"],
    kind: "Button group",
  },
  {
    id: "game-dialogue-display",
    sectionId: "game-presentation",
    label: "Game Dialogue Display",
    description: "Choose a classic dialogue box or segment history display.",
    aliases: ["game", "vn", "history"],
    kind: "Button group",
  },
  {
    id: "game-text-effects",
    sectionId: "game-presentation",
    label: "Game text effects",
    description: "Animate dramatic words and explicit text-effect tags in Game mode.",
    aliases: ["game", "text", "animation", "effects", "accessibility", "motion"],
    keywords: ["animated text", "dramatic text"],
    kind: "Toggle",
  },
  {
    id: "weather-effects",
    sectionId: "motion-backgrounds",
    label: "Dynamic weather effects",
    description: "Show animated weather particles from story context.",
    aliases: ["weather", "rain", "snow", "fog"],
    keywords: ["rain effect", "snow effect", "weather animation"],
    kind: "Toggle",
  },
  {
    id: "release-channel",
    sectionId: "updates",
    label: "Release Channel",
    description: "Choose which release channel update checks follow.",
    aliases: ["updates", "branch", "version"],
    keywords: ["beta channel", "stable channel"],
    kind: "Select",
  },
  {
    id: "restart-server",
    sectionId: "admin-access",
    label: "Restart Server",
    description: "Gracefully restart the Marinara server from this browser.",
    aliases: ["server", "restart", "maintenance", "remote"],
    keywords: ["reboot server", "restart app"],
    kind: "Button group",
  },
  {
    id: "copy-support-diagnostics",
    sectionId: "support-diagnostics",
    label: "Copy Diagnostics",
    description: "Copy version, build, system, GPU, and active model details for support.",
    aliases: ["support", "diagnostics", "system info", "gpu", "model", "clipboard"],
    kind: "Button group",
  },
  {
    id: "custom-generation-parameters",
    sectionId: "parameters",
    label: "Custom generation parameters",
    description: "Create reusable numeric provider parameters for chats and connections.",
    aliases: ["parameter", "provider", "min p", "min_p", "range", "tooltip"],
    kind: "Input",
  },
  {
    id: QUICK_REPLIES_SETTINGS_CONTROL_ID,
    sectionId: "input-editing",
    label: "Quick replies",
    description: "Show alternate draft actions beside Send.",
    aliases: ["post only", "guide reply", "impersonate"],
    kind: "Toggle",
  },
  {
    id: "show-message-timestamps",
    sectionId: "message-tools",
    label: "Show message timestamps",
    description: "Display date and time on chat messages.",
    aliases: ["time", "date", "metadata"],
    kind: "Toggle",
  },
  {
    id: "show-model-name",
    sectionId: "message-tools",
    label: "Show model name on messages",
    description: "Display which AI model generated each response.",
    aliases: ["model", "metadata"],
    kind: "Toggle",
  },
  {
    id: "show-token-usage",
    sectionId: "message-tools",
    label: "Show token usage on messages",
    description: "Display prompt and completion token counts.",
    aliases: ["tokens", "context", "cost"],
    // F6 (O5): "context length"/"context size" sent a user trying to raise the
    // model's context window here instead and Enter silently flipped this
    // toggle - removed; there is no context-size control in this registry.
    kind: "Toggle",
  },
  {
    id: "show-context-usage",
    sectionId: "message-tools",
    label: "Show context usage",
    description: "Show the latest context usage in connection switchers.",
    aliases: ["context usage", "context meter"],
    kind: "Toggle",
  },
  {
    id: "show-message-numbers",
    sectionId: "message-tools",
    label: "Show message numbers",
    description: "Display message numbers in chats.",
    aliases: ["metadata", "index"],
    kind: "Toggle",
  },
  {
    id: "guide-generations",
    sectionId: "message-tools",
    label: "Guide swipes/regens with chat input",
    description: "Use the current draft as regeneration direction.",
    aliases: ["guided", "regenerate", "swipes"],
    kind: "Toggle",
  },
  {
    id: "include-reasoning-in-exports",
    sectionId: "message-tools",
    label: "Include reasoning in exports",
    description: "Include hidden thinking metadata in chat exports.",
    aliases: ["reasoning", "thinking", "exports"],
    kind: "Toggle",
  },
  {
    id: "include-private-notes-in-exports",
    sectionId: "message-tools",
    label: "Include private notes in exports",
    description: "Include your private message notes in chat exports.",
    aliases: ["notes", "private", "exports"],
    kind: "Toggle",
  },
  {
    id: "debug-mode",
    sectionId: "message-tools",
    label: "Debug mode",
    description: "Log model payloads in the server console.",
    aliases: ["debug", "logs", "prompt", "console"],
    kind: "Toggle",
  },
  {
    id: "automatic-backups",
    sectionId: "backup-export",
    label: "Automatic backups",
    description: "Schedule full backups and choose how many automatic archives to retain.",
    aliases: ["backup", "daily", "weekly", "monthly", "scheduled"],
    keywords: ["auto backup", "scheduled backup"],
    kind: "Toggle",
  },
  {
    id: "automatic-backups-kept",
    sectionId: "backup-export",
    label: "Automatic backups kept",
    description: "Retain between 1 and 9999 automatic backup archives without affecting manual backups.",
    aliases: ["backup", "retention", "history", "rotate", "automatic"],
    keywords: ["backup retention", "how many backups"],
    kind: "Input",
  },
  {
    id: "avatar-storage-optimization",
    sectionId: "storage-optimization",
    label: "Optimize avatar storage",
    description: "Find old avatar image files that are no longer referenced by Marinara data.",
    aliases: ["storage", "avatar", "cleanup", "orphan", "abandoned", "disk space"],
    keywords: ["disk cleanup", "free space"],
    kind: "Button group",
  },
] as const;

export function searchSettings(query: string, localize: (englishText: string) => string): SettingsSearchResult[] {
  const normalized = query.trim().toLowerCase();
  if (!normalized) return [];
  const parts = normalized.split(/\s+/u).filter(Boolean);

  const controlResults = SETTINGS_SEARCHABLE_CONTROLS.flatMap((control) => {
    const section = SETTINGS_SECTION_BY_ID.get(control.sectionId);
    if (!section) return [];
    const haystack = [
      control.label,
      localize(control.label),
      control.description,
      localize(control.description),
      control.kind,
      localize(control.kind),
      section.label,
      localize(section.label),
      section.description,
      localize(section.description),
      ...control.aliases,
    ]
      .join(" ")
      .toLowerCase();
    return parts.every((part) => haystack.includes(part)) ? [{ type: "control" as const, control, section }] : [];
  });

  const sectionResults = SETTINGS_SECTIONS.filter((section) => {
    const haystack = [
      section.label,
      localize(section.label),
      section.description,
      localize(section.description),
      ...section.aliases,
    ]
      .join(" ")
      .toLowerCase();
    return parts.every((part) => haystack.includes(part));
  }).map((section) => ({ type: "section" as const, section }));

  return [...controlResults, ...sectionResults];
}
